apiVersion: batch/v1
kind: CronJob
metadata:
  name: rsync-host-to-usb
  labels:
    app: rsync
spec:
  # CHANGE THIS: Set your cron schedule (currently: daily at midnight)
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          # CHANGE THIS: Set to your Kubernetes node name where the USB is connected
          nodeName: node100
          containers:
            - name: rsync
              image: ghcr.io/goingoffroading/rsync:v1.0
              securityContext:
                privileged: true
              env:
                # CHANGE THIS: Customize rsync command (e.g., add --exclude patterns)
                - name: RSYNC_COMMAND
                  value: "rsync -avh --progress --delete --exclude='Stuff/Things'"
                # CHANGE THIS: Target directory on USB drive (must exist or job will fail)
                - name: USB_TARGET_DIR
                  value: "/usb/backup"
              volumeMounts:
                - name: host-data
                  mountPath: /host
                  readOnly: true
                - name: usb-data
                  mountPath: /dev/sdc1
          volumes:
            - name: host-data
              hostPath:
                path: /host
                # CHANGE THIS: Verify the path type matches your setup
                type: Directory
            - name: usb-data
              hostPath:
                # CHANGE THIS: Set to your USB device path (e.g., /dev/sdc1)
                path: /dev/sdc1
                # CHANGE THIS: Use BlockDevice for raw device, or Directory if pre-mounted
                type: BlockDevice
